services:
  nginx:
    build:
      context: .

    environment:
      DOMAIN_NAME: "${DOMAIN_NAME}"

    volumes:
      - type: bind
        source: ./.nginx/templates
        target: /etc/nginx/templates
        read_only: true

      - type: bind
        source: "${LETSENCRYPT_FILES}"
        target: /srv/challenge
        read_only: true

      - type: bind
        source: "${OPENSSL_FILES}"
        target: /etc/nginx/ssl
        read_only: true

    ports:
      - name: http-port
        target: 80
        published: "${HTTP_PORT-80}"
        app_protocol: http

      - name: https-port
        target: 443
        published: "${HTTPS_PORT-443}"
        app_protocol: https

    network_mode: bridge

    extra_hosts:
      - "host.docker.internal:host-gateway"
