name: Deploy to S3
on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Wasm-Pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Test Firefox
        run: wasm-pack test --headless --firefox

      - name: Test Chrome
        run: wasm-pack test --headless --chrome

  DeployToS3:
    needs: Test
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TRUNK_VERSION: v0.16.0
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_BUCKET_REGION }}

      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/${{ env.TRUNK_VERSION }}/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      - name: Build WASM
        run: ./trunk build --release

      - name: Deploy to S3
        run: aws s3 sync dist s3://${{ secrets.S3_BUCKET }} --region ${{ secrets.S3_BUCKET_REGION }} --delete
